<?php
/**
 * @file
 * Code for the ACME Discussion feature.
 */

include_once 'acme_discussion.features.inc';


/**
 * Implementation of hook_block_info()
 */
function acme_discussion_block_info() {
  $blocks = array();
  
  $blocks['acme_discussion_discussion'] = array(
    'info'  => t('ACME Discussion: Discussions on Group/Show Page'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}


/**
 * Implementation of hook_block_view()
 */
function acme_discussion_block_view($delta = '') {
  $block = array();
  
  switch($delta) {
    case 'acme_discussion_discussion':
      if(module_exists('acme_profile_base')) {
        $interests = acme_profile_base_get_interest();
        $interests = implode('+', $interests);
        if($interests == '') {
          // interests: make use of the default argument handling
          $interests = NULL;
        }
      }
      
      // group id: make use of default argument handling
      $group_nid = NULL;
      
      $block['subject'] = t('Active Conversations');
      $block['content'] = views_embed_view(
        'acme_discussion',
        'block',
        $group_nid,
        $interests
      );
      break;
  }
  
  return $block;
}