<?php
/**
 * @file
 * Code for the ACME Episode feature.
 */

include_once 'acme_episode.features.inc';


/**
 * Implementation of hook_block_info()
 */
function acme_episode_block_info() {
  $blocks = array();
  
  $blocks['acme_episode_latest_episode'] = array(
    'info'  => t('ACME Episode: Latest Episode'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['acme_episode_on_tonight'] = array(
    'info'  => t('ACME Episode: On Tonight'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}


/**
 * Implementation of hook_block_view()
 */
function acme_episode_block_view($delta = '') {
  $block = array();
  
  switch($delta) {
    case 'acme_episode_latest_episode':
      if(module_exists('acme_profile_base')) {
        $interests = acme_profile_base_get_interest();
        $interests = implode('+', $interests);
        if($interests == '') {
          // interests: make use of the default argument handling
          $interests = NULL;
        }
      }
      
       // group id: make use of default argument handling
      $group_nid = NULL;
      
      $block['subject'] = '';
      $block['content'] = views_embed_view(
        'acme_episode_latest_episode',
        'block',
        $group_nid,
        $interests
      );
      
      break;
    case 'acme_episode_on_tonight':
      if(module_exists('acme_profile_base')) {
        $interests = acme_profile_base_get_interest();
        $interests = implode('+', $interests);
        if($interests == '') {
          // interests: make use of the default argument handling
          $interests = NULL;
        }
      }
      
      $block['subject'] = '';
      $block['content'] = views_embed_view(
        'acme_episode_on_tonight',
        'block',
        $interests
      );
      
      break;
  }
  
  return $block;
}