<?php

/**
 * Implementation of hook_menu()
 */
function acme_central_menu() {
  $items = array();

  $items['admin/test'] = array(
    'title'            => t('Admin Test'),
    'page callback'    => 'acme_central_dev_test',
    'access arguments' => array('access administration pages'),
    'type'             => MENU_CALLBACK,
  );

  return $items;
}


/**
  * Developers can use to test their functions.
  *
  */
function acme_central_dev_test() {

  return '';
}


/**
 * Exports a variable
 *
 * @param $var The variable to be exported
 */
function acme_central_debug($var) {
  drupal_set_message('<xmp>'. var_export($var, 1) .'</xmp>');
}
