<?php
/**
 * @file
 * Code for the acme_banner feature.
 */

include_once 'acme_banner.features.inc';

/**
 * Implementation of hook_image_styles_alter()
 */
function acme_banner_image_styles_alter(&$styles) {

  if(isset($styles['flexslider_full'])) {
    foreach($styles['flexslider_full']['effects'] as $i => $effect) {
      if($effect['name'] == 'image_scale_and_crop') {
        $styles['flexslider_full']['effects'][$i]['data']['width']  = 900;
        $styles['flexslider_full']['effects'][$i]['data']['height'] = 380;
      }
    }
  }
}